default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
  username: <%= 'roman' %>
  password: <%= '1234' %>

development:
  <<: *default
  database: online_store_development

test:
  <<: *default
  database: online_store_test
